server.port=9090
spring.application.name=security

spring.security.user.password=user

# SWAGGER
springdoc.swagger-ui.path=/swagger
springdoc.api-docs.path=/swagger-docs
springdoc.swagger-ui.operationsSorter=method
